baseURL = "https://cowleycomputing.com"
languageCode = "en-us"
title = "Erik's Notes"
theme="archie"
#copyright = "© Athul"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

pagination.pagerSize = 5 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	#subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
    noComment = true
    mainSections = ["cs"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/five-hundred-eleven"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Computing notes"
url = "/cs"
weight = 5

[[menu.main]]
name = "Misc notes"
url = "/misc"
weight = 6

[[menu.main]]
name = "About"
url = "/about"
weight = 10
